name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build all packages
        run: bun run build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    if: gitea.event_name == 'push' && gitea.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Gitea Registry
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
          REGISTRY_USER: ${{ vars.REGISTRY_USER }}
        run: |
          echo "$REGISTRY_TOKEN" | docker login gitea.escu.dev -u "$REGISTRY_USER" --password-stdin

      - name: Build Docker image
        env:
          IMAGE_NAME: gitea.escu.dev/${{ gitea.repository }}
          IMAGE_TAG: ${{ gitea.sha }}
        run: |
          docker build -t "$IMAGE_NAME:latest" -t "$IMAGE_NAME:$IMAGE_TAG" .

      - name: Push Docker image
        env:
          IMAGE_NAME: gitea.escu.dev/${{ gitea.repository }}
          IMAGE_TAG: ${{ gitea.sha }}
        run: |
          docker push "$IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:$IMAGE_TAG"

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [docker]
    if: gitea.event_name == 'push' && gitea.ref == 'refs/heads/main'
    steps:
      - name: Setup kubectl
        run: |
          curl -sLO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl && mv kubectl /usr/local/bin/

      - name: Configure kubeconfig
        env:
          KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG_CONTENT" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Kubernetes
        env:
          IMAGE_NAME: gitea.escu.dev/${{ gitea.repository }}
        run: |
          NAMESPACE="meowtern-prod"
          APP_NAME="meowtern"

          # Create namespace if not exists
          kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

          # Apply manifests
          kubectl apply -f - <<EOF
          ---
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: ${APP_NAME}
            namespace: ${NAMESPACE}
            labels:
              app: ${APP_NAME}
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: ${APP_NAME}
            template:
              metadata:
                labels:
                  app: ${APP_NAME}
              spec:
                containers:
                - name: ${APP_NAME}
                  image: ${IMAGE_NAME}:latest
                  imagePullPolicy: Always
                  ports:
                  - containerPort: 80
                  resources:
                    limits:
                      cpu: "500m"
                      memory: "512Mi"
                    requests:
                      cpu: "50m"
                      memory: "64Mi"
                nodeSelector:
                  role: homelab-worker
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: ${APP_NAME}
            namespace: ${NAMESPACE}
          spec:
            type: ClusterIP
            selector:
              app: ${APP_NAME}
            ports:
            - port: 80
              targetPort: 80
          ---
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: ${APP_NAME}
            namespace: ${NAMESPACE}
            annotations:
              traefik.ingress.kubernetes.io/router.tls: "true"
          spec:
            tls:
            - hosts:
              - project-meowtern.escu.dev
            rules:
            - host: project-meowtern.escu.dev
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: ${APP_NAME}
                      port:
                        number: 80
          EOF

          # Force rollout to pull latest image
          kubectl rollout restart deployment/${APP_NAME} -n ${NAMESPACE}

          # Wait for rollout to complete
          kubectl rollout status deployment/${APP_NAME} -n ${NAMESPACE} --timeout=120s
