name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build all packages
        run: bun run build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    if: gitea.event_name == 'push' && gitea.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Gitea Registry
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
          REGISTRY_USER: ${{ vars.REGISTRY_USER }}
        run: |
          echo "$REGISTRY_TOKEN" | docker login gitea.escu.dev -u "$REGISTRY_USER" --password-stdin

      - name: Build Docker image
        env:
          IMAGE_NAME: gitea.escu.dev/${{ gitea.repository }}
          IMAGE_TAG: ${{ gitea.sha }}
        run: |
          docker build -t "$IMAGE_NAME:latest" -t "$IMAGE_NAME:$IMAGE_TAG" .

      - name: Push Docker image
        env:
          IMAGE_NAME: gitea.escu.dev/${{ gitea.repository }}
          IMAGE_TAG: ${{ gitea.sha }}
        run: |
          docker push "$IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:$IMAGE_TAG"
