name: Preview Cleanup

on:
  pull_request:
    types: [closed]

env:
  REGISTRY: git.escu.dev
  IMAGE_NAME: git.escu.dev/${{ gitea.repository }}
  GITEA_API: https://git.escu.dev
  PR_NUMBER: ${{ gitea.event.pull_request.number }}

jobs:
  cleanup-preview:
    name: Cleanup Preview
    runs-on: ubuntu-latest
    steps:
      - name: Setup kubectl
        run: |
          curl -sLO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl && mv kubectl /usr/local/bin/

      - name: Configure kubeconfig
        env:
          KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG_CONTENT" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Delete preview namespace
        run: |
          NAMESPACE="preview-pr-${{ env.PR_NUMBER }}"

          # Delete namespace (cascades all resources)
          kubectl delete namespace "$NAMESPACE" --ignore-not-found=true --wait=true --timeout=120s

          echo "Preview environment for PR #${{ env.PR_NUMBER }} has been cleaned up"

      - name: Delete container images
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        run: |
          # Delete PR-specific tags from Gitea container registry
          REPO_PATH=$(echo "${{ gitea.repository }}" | tr '[:upper:]' '[:lower:]')

          curl -s -H "Authorization: token $REGISTRY_TOKEN" \
            "${{ env.GITEA_API }}/api/v1/packages/${{ gitea.repository_owner }}/container/${REPO_PATH##*/}/versions" | \
            jq -r '.[] | select(.version | startswith("pr-${{ env.PR_NUMBER }}")) | .id' | \
            while read -r VERSION_ID; do
              if [ -n "$VERSION_ID" ]; then
                echo "Deleting image version: $VERSION_ID"
                curl -s -X DELETE -H "Authorization: token $REGISTRY_TOKEN" \
                  "${{ env.GITEA_API }}/api/v1/packages/${{ gitea.repository_owner }}/container/${REPO_PATH##*/}/versions/$VERSION_ID" || true
              fi
            done

      - name: Comment on PR
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        run: |
          curl -s -X POST \
            -H "Authorization: token $REGISTRY_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"body": "Preview environment has been cleaned up."}' \
            "${{ env.GITEA_API }}/api/v1/repos/${{ gitea.repository }}/issues/${{ env.PR_NUMBER }}/comments"
