name: Preview Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  REGISTRY: git.escu.dev
  IMAGE_NAME: git.escu.dev/${{ gitea.repository }}
  GITEA_API: https://git.escu.dev
  PR_NUMBER: ${{ gitea.event.pull_request.number }}
  NODE_IP: "10.0.10.5"

jobs:
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set pending status
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        run: |
          curl -s -X POST \
            -H "Authorization: token $REGISTRY_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"state": "pending", "target_url": "${{ env.PREVIEW_URL }}", "description": "Preview deployment in progress...", "context": "preview"}' \
            "${{ env.GITEA_API }}/api/v1/repos/${{ gitea.repository }}/statuses/${{ gitea.sha }}"

      - name: Login to Registry
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
          REGISTRY_USER: ${{ vars.REGISTRY_USER }}
        run: |
          printf '%s' "$REGISTRY_TOKEN" | docker login ${{ env.REGISTRY }} -u "$REGISTRY_USER" --password-stdin

      - name: Build and Push
        run: |
          docker build -t "${{ env.IMAGE_NAME }}:pr-${{ env.PR_NUMBER }}" .
          docker push "${{ env.IMAGE_NAME }}:pr-${{ env.PR_NUMBER }}"

      - name: Setup kubectl
        run: |
          curl -sLO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl && mv kubectl /usr/local/bin/

      - name: Configure kubeconfig
        env:
          KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG_CONTENT" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy Preview
        run: |
          NAMESPACE="preview-pr-${{ env.PR_NUMBER }}"
          APP_NAME="meowtern"
          IMAGE="${{ env.IMAGE_NAME }}:pr-${{ env.PR_NUMBER }}"

          # Create namespace
          kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
          kubectl label namespace "$NAMESPACE" preview.homelab/managed=true preview.homelab/pr-number="${{ env.PR_NUMBER }}" --overwrite

          # Apply manifests (NodePort for internal access)
          kubectl apply -f - <<EOF
          ---
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: ${APP_NAME}-pr-${{ env.PR_NUMBER }}
            namespace: ${NAMESPACE}
            labels:
              app: ${APP_NAME}
              preview: "true"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: ${APP_NAME}
            template:
              metadata:
                labels:
                  app: ${APP_NAME}
              spec:
                containers:
                - name: ${APP_NAME}
                  image: ${IMAGE}
                  imagePullPolicy: Always
                  ports:
                  - containerPort: 80
                  resources:
                    limits:
                      cpu: "500m"
                      memory: "512Mi"
                    requests:
                      cpu: "50m"
                      memory: "64Mi"
                nodeSelector:
                  role: homelab-worker
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: ${APP_NAME}-pr-${{ env.PR_NUMBER }}
            namespace: ${NAMESPACE}
          spec:
            type: NodePort
            selector:
              app: ${APP_NAME}
            ports:
            - port: 80
              targetPort: 80
          EOF

          # Wait for deployment
          kubectl rollout status deployment/${APP_NAME}-pr-${{ env.PR_NUMBER }} -n ${NAMESPACE} --timeout=120s

          # Get the NodePort and save for later steps
          NODE_PORT=$(kubectl get svc ${APP_NAME}-pr-${{ env.PR_NUMBER }} -n ${NAMESPACE} -o jsonpath='{.spec.ports[0].nodePort}')
          echo "Preview available at: http://${{ env.NODE_IP }}:${NODE_PORT}"
          # Save to file for other steps
          echo "${NODE_PORT}" > /tmp/node_port

      - name: Set success status
        if: success()
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        run: |
          # Read the NodePort from the deploy step
          NODE_PORT=$(cat /tmp/node_port)
          PREVIEW_URL="http://${{ env.NODE_IP }}:${NODE_PORT}"

          echo "Setting success status with preview URL: ${PREVIEW_URL}"

          curl -s -X POST \
            -H "Authorization: token $REGISTRY_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"state\": \"success\", \"target_url\": \"${PREVIEW_URL}\", \"description\": \"Preview deployed!\", \"context\": \"preview\"}" \
            "${{ env.GITEA_API }}/api/v1/repos/${{ gitea.repository }}/statuses/${{ gitea.sha }}"

          # Save PREVIEW_URL for comment step
          echo "${PREVIEW_URL}" > /tmp/preview_url

      - name: Comment on PR
        if: success()
        continue-on-error: true
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        run: |
          DEBUG_FILE="/.cache/comment-debug-${{ gitea.sha }}.log"
          exec > >(tee -a "$DEBUG_FILE") 2>&1

          echo "=== COMMENT DEBUG $(date) ==="
          PREVIEW_URL=$(cat /tmp/preview_url)
          echo "Preview URL: ${PREVIEW_URL}"
          echo "Gitea API: ${{ env.GITEA_API }}"
          echo "Repository: ${{ gitea.repository }}"
          echo "PR Number: ${{ env.PR_NUMBER }}"
          echo "Token length: ${#REGISTRY_TOKEN}"

          # Create comment body with proper JSON escaping (no jq needed)
          BODY="## Preview Deployment\n\n**URL:** ${PREVIEW_URL}\n\n**Commit:** \`${{ gitea.sha }}\`\n\n_(Internal network only)_\n\nThis preview will be automatically destroyed when the PR is closed."

          echo "Posting comment..."
          RESPONSE=$(curl -s -w "\nHTTP_CODE:%{http_code}" -X POST \
            -H "Authorization: token $REGISTRY_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"${BODY}\"}" \
            "${{ env.GITEA_API }}/api/v1/repos/${{ gitea.repository }}/issues/${{ env.PR_NUMBER }}/comments")

          HTTP_CODE=$(echo "$RESPONSE" | grep "HTTP_CODE:" | cut -d: -f2)
          BODY_RESPONSE=$(echo "$RESPONSE" | grep -v "HTTP_CODE:")

          echo "Response code: $HTTP_CODE"
          echo "Response body: $BODY_RESPONSE"

          if [ "$HTTP_CODE" = "201" ]; then
            echo "Comment posted successfully!"
          else
            echo "Failed to post comment (HTTP $HTTP_CODE)"
          fi

      - name: Set failure status
        if: failure()
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        run: |
          curl -s -X POST \
            -H "Authorization: token $REGISTRY_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"state": "failure", "target_url": "", "description": "Preview deployment failed", "context": "preview"}' \
            "${{ env.GITEA_API }}/api/v1/repos/${{ gitea.repository }}/statuses/${{ gitea.sha }}"
